version: 2

models:
  - name: silver_transactions
    description: "Cleaned retail transaction grain = 1 invoice line (or 1 row per invoice record, depending on source)."
    columns:
      - name: invoice_no
        tests: [not_null]
      - name: customer_id
        tests: [not_null]
      - name: invoice_ts
        tests: [not_null]

  - name: silver_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: silver_sessions
    columns:
      - name: user_id
        tests: [not_null]